gis/urls.py
from django.urls import path
from gis import views
app_name = 'gis'

urlpatterns = [
    path('gis/',views.index,name='index'),
    path('gis/addMarker1/',views.add_marker1,name='add_marker1'),
    path('gis/addMarker2/',views.add_marker2,name='add_marker2'),
    path('gis/getMarker/',views.ajax_get_marker_list,name='get_marker'),
    path('gis/add/',views.add_matker_ajax,name='add'),
    path('gis/search/',views.search,name="search"),
    path('gis/ajax/search/',views.ajax_search,name="ajax_search"),
    path('gis/route/',views.route_plan,name="route_plan"),
    path("gis/admin/",views.data_admin,name='data_admin'),
    path("gis/ajax/edit",views.edit,name='edit'),
    path("gis/admin/edit/<int:id>",views.edit_page,name="edit_page"),
    path("gis/admin/delete/<int:id>",views.delete,name="delete"),
    path("gis/admin/search/",views.admin_search,name="admin_search"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from gis import urls as gis_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(gis_urls,namespace='gis')),
]

gis/models.py
from django.db import models

# Create your models here.
class Marker(models.Model):
    title = models.CharField(max_length=100)
    lng = models.DecimalField(max_digits=9,decimal_places=6)#最大长度和小数最大位数
    lat = models.DecimalField(max_digits=9,decimal_places=6)
    content = models.TextField()
    def __str__(self):
        return self.title

'''
class Detail(models.Model):
    marker = models.ForeignKey(Marker,on_delete=models.CASCADE)
    body = models.TextField()
    def __str__(self):
        return self.name
'''

gis/views.py
from django.shortcuts import render,redirect
from gis.models import Marker
from django.http import JsonResponse
# Create your views here.

def index(request):
    #return render(request,'gis/indexbaiduapi.html')
    return render(request,'gis/map.html',{'enableGetPoint':0})

def add_marker1(request):
    return render(request,'gis/form_basic.html')

def add_marker2(request):
    return render(request,'gis/right.html',{'enableGetPoint':1})
    
def add_matker_ajax(request):
    result = {'status':"True",'message':''}
    if request.method == 'POST':
        marker = {
            'title': request.POST.get('title'),
            'lng':request.POST.get('lng'),
            'lat':request.POST.get('lat'),
            'content':request.POST.get('content')
        }
        Marker.objects.create(**marker)
        result['message'] = 'add success'    
    else :
        result['status'] = "False"
        result['message'] = 'only method post'
        
    return JsonResponse(result,safe=False)    

def ajax_get_marker_list(request):
    markers = Marker.objects.all()#取出所有的marker
    marker = []
    for _ in markers:
        dict_of_marker = {}
        dict_of_marker['title'] = _.title
        dict_of_marker['lng'] = _.lng
        dict_of_marker['lat'] = _.lat
        dict_of_marker['content'] = _.content
        marker.append(dict_of_marker)
    return JsonResponse(marker,safe=False)

def search(request):
    return render(request,'gis/search.html')

def ajax_search(request):
    title = request.POST.get('title')
    result = {'status':"False",}
    try:
        result_set = Marker.objects.get(title=title)
    except Exception:
        result_set = None
        print('查找失败')
    if result_set is not None:
        result["status"] = "True"
        result["title"] = result_set.title
        result["lng"] = result_set.lng
        result['lat'] = result_set.lat
        result["content"] = result_set.content        
    return JsonResponse(result,safe=False)
def route_plan(request):
    return render(request,'gis/route_plan.html')
def data_admin(request):
    markers = Marker.objects.all()
    counts = len(markers)
    content = {"markers":markers,'counts':counts}
    return render(request,'gis/admin.html',content)
    
def edit(request):
    result = {"status":"False","message":''}
    if request.method == 'POST':
        title = request.POST.get("title")
        lng = request.POST.get("lng")
        lat = request.POST.get("lat")
        content = request.POST.get("content")
        m_id = request.POST.get("id")
        try:
            marker = Marker.objects.get(id=m_id)
            marker.title = title
            marker.lng = lng
            marker.lat = lat
            marker.content = content
            marker.save()
        except Exception:
            result["message"] = "更新数据库失败"
        result["status"] = "True"
        
    else:
        result["message"] = "only POST"
        
    return JsonResponse(result,safe=False)

def edit_page(request,id):
    marker = Marker.objects.get(id=id)
    content = {"marker":marker}
    return render(request,'gis/edit.html',content)
    
def delete(request,id):
    try:
        Marker.objects.get(id=id).delete()
    except Exception :
        #result['msg'] = "删除失败"
        print("删除失败")    
    return redirect("gis:data_admin")
    
def admin_search(request):
    title = request.GET.get('search')
    try :
        marker = Marker.objects.get(title=title)
    except Exception:
        markers = None
        counts = 0
    markers=[]
    markers.append(marker)
    counts = 1
    content = {'markers':markers,"counts":counts}
    return render(request,'gis/admin.html',content)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

templates/gis/admin.html
{% extends 'gis/indexDemo.html' %} 
{% block title %}后台数据管理{% endblock title %}
{% block content %}
<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="card-box">
					<!-- Row start -->
					<div class="am-g">
					    
						<div class="am-u-sm-12 am-u-md-6">
						<!--
				          <div class="am-btn-toolbar">
				            <div class="am-btn-group am-btn-group-xs">
				              
				              <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> 删除</button>
				            </div>
				          </div>
				          -->	
				        </div>
				        
				        
						<div class="am-u-sm-12 am-u-md-3">
						  <form action="{% url 'gis:admin_search' %}">
				          <div class="am-input-group am-input-group-sm">
				            <input type="text" name="search" class="am-form-field" required>
				          <span class="am-input-group-btn">
				            <button class="am-btn am-btn-default" type="submit">搜索</button>
				          </span>
				          </div>
				        </div>
				      </div>
					  <!-- Row end -->
					  
					  <!-- Row start -->
					  	<div class="am-g">
        <div class="am-u-sm-12">
          <form class="am-form">
            <table class="am-table am-table-striped am-table-hover table-main">
              <thead>
              <tr>
                <!--<th class="table-check"><input type="checkbox" /></th>--><th class="table-id">ID</th><th class="table-title">地名</th><th class="table-type">经度</th><th class="table-author am-hide-sm-only">纬度</th><th class="table-date am-hide-sm-only">描述</th><th class="table-set">操作</th>
              </tr>
              </thead>
              <tbody>
              {% for marker in markers %}
              <tr>
                <!--<td><input type="checkbox" value="{{marker.id}}"/></td>-->
                <td>{{marker.id}}</td>
                <td><a href="{% url 'gis:edit_page' marker.id %}">{{marker.title}}</a></td>
                <td>{{marker.lng}}</td>
                <td class="am-hide-sm-only">{{marker.lat}}</td>
                <td class="am-hide-sm-only">{{marker.content}}</td>
                <td>
                  <div class="am-btn-toolbar">
                    <div class="am-btn-group am-btn-group-xs">
                      <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span class="am-icon-pencil-square-o"></span><a href="{% url 'gis:edit_page' marker.id %}"> 编辑</a></button>
                      <button class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span class="am-icon-trash-o"></span><a href="{% url 'gis:delete' marker.id %}" onclick="return confirmDel();"> 删除</button>
                    </div>
                  </div>
                </td>
              </tr>
              {% empty %}
              没有数据
              {% endfor %}
              </tbody>
            </table>
            <div class="am-cf">
              共 {{counts}} 条记录            
          </form>
        </div>

      </div>
					  <!-- Row end -->
					  
					</div>
				
				
				
				
				</div>
			

			</div>
		</div>
<script>
function confirmDel(){
    var msg = window.confirm("确认删除？");
    if(msg){
        return true;
    }
    else{
        return false;
    }
}

    
</script>
{% endblock content %}

templates/gis/edit.html
{% extends 'gis/indexDemo.html' %}
{% block title%}后台数据管理{% endblock title %}
{% block content %}
<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="am-g">
					<!-- Row start -->
						<div class="am-u-sm-12">
							<div class="card-box">
								
								<form class="am-form">
								  
								    <legend>标注信息编辑</legend>
								    <div class="am-form-group">
								      <label for="doc-vld-name-2">地点名：</label>
								      <input type="text" id="title" value="{{marker.title}}" placeholder="输入地点名" required/>
								    </div>
								
								    <div class="am-form-group">
								      <label for="doc-vld-email-2">经度：</label>
								      <input type="text" id="lng" value="{{marker.lng}}" placeholder="输入经度" required/>
								    </div>
								
								    <div class="am-form-group">
								      <label for="doc-vld-url-2">纬度：</label>
								      <input type="text" id="lat" value="{{marker.lat}}" placeholder="输入纬度" required/>
								    </div>
								
								    <div class="am-form-group">
								      <label for="doc-vld-age-2">描述：</label>
								      <textarea class="am-u-md-10 form-control" rows="5" id="content" placeholder="输入地点的介绍/描述">{{marker.content}}</textarea>
								    </div>
								    <button type="button" onclick="update();">提交</button>
								    
								  
								</form>
								
								
							</div>
						</div>
					<!-- Row end -->
				</div>
			
			</div>
		</div>
		
<script>

function update(){
    var title = $("#title").val();
    var lng = $("#lng").val();
    var lat = $("#lat").val();
    var content = $("#content").val();
    var id = {{marker.id}};
    alert(title+","+lng+","+lat);
    if(title != '' && lng != '' && lat != '' && content != ''){
        $.post(
            "{% url 'gis:edit' %}",
            {"title":title,"lng":lng,"lat":lat,"content":content,"id":id},
            function(ret){
                if(ret.status === "True"){
                    alert("更新成功");
                    location.href="{% url 'gis:data_admin' %}";
                }
                else{
                    alert("更新失败");
                }
            }
        );
    }
}
</script>
{% endblock content %}

templates/gis/form_basic.html
{% extends 'gis/indexDemo.html' %}
{% block title %}增加地点{% endblock title %}
{% block content %}
<div class="content-page">
<div class="card-box">
	<h4 class="header-title m-t-0 m-b-30">增加地点</h4>
		<form class="am-form">
		    
			<div class="am-form-group">
				<label >地点名字</label>
				<input id="title" type="text" class="am-radius" placeholder="输入地名/建筑物名字">
				<label>经度:<span id="lngview"></span></label>
				<br>
				<label>纬度:<span id="latview"></span></label>
				<input id="lng" type="hidden">
				<input id="lat" type="hidden">
				<textarea class="am-u-md-10 form-control" rows="5" id="content" placeholder="输入地点的介绍/描述"></textarea>
			</div>
		    <button type="button" onclick="add();">增加</button>
		    <span id="status"></span>
	    </form>
</div>
</div>
<script> 
    myValue1 = '';
	loadMapAutocomplete("title");
    function loadMapAutocomplete(title) {
        var checkValue;
        Ac = new BMap.Autocomplete( //建立一个自动完成的对象
            {
                "input": title,
            });
        
        
        Ac.addEventListener("onconfirm", function(e) {    //鼠标点击下拉列表后的事件
	    var _value = e.item.value;
		myValue = _value.district + _value.street +  _value.business;
		myValue1 = _value.street +  _value.business;//用于保存到数据库
		$("#title").val(myValue1);
		//测试
		//alert(myValue)
		//$("#title").val(myValue1);
		//把地点转换成坐标
        // 创建地址解析器实例
        var myGeo = new BMap.Geocoder();
        // 将地址解析结果显示
        myGeo.getPoint(myValue, function(point){
            if (point) {
                $('#lngview').html(point.lng);
                $('#latview').html(point.lat);
                $("#lng").val(point.lng);
                $("#lat").val(point.lat);
            }
            else {
                $('#lng').html("无效地址");
                $('#lat').html("无效地址");
            }    
        },"南昌市");
		
	    });
        
    }
    
    // 提交数据
    function add(){
        var title = $("#title").val();
        //var title = myValue1;//默认获取鼠标点击地址输入提示后得到的已剪切的地址
        //如果不是点击的地址输入提示，则获取输入框的内容
        //if(title === ''){
        //    title = $("#title").val();
        //}
        var lng = $("#lng").val();
        var lat = $("#lat").val();
        var content = $("#content").val();
        //alert(title + "," + lng + "," + lat + "," + content)
        alert(title);
        if(title != "" && content != "" && lng != "" && lat != ""){
            $.post(
                "{% url 'gis:add' %}",
                {'title':title,'lng':lng,'lat':lat,'content':content}, 
                function(ret){
                    if(ret.status === 'True'){
                        $('#status').html(ret.message);
                        //location.href="{% url 'gis:index' %}";
                    }
                    else{
                        $('#status').html(ret.message);
                    }
                }
            )
        }
        else{
            alert("请输入完整信息");
        }
    }
</script>
{% endblock content %}

templates/gis/indexDemo.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>南工GIS</title>
		<link rel="stylesheet" href="{% static 'assets/css/amazeui.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/core.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/menu.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/index.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/admin.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/page/typography.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/page/form.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/component.css' %}" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
        <script type="text/javascript" src="{% static 'assets/js/jquery-2.1.0.js' %}" ></script>
        <!--引用百度地图API-->
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=GZvFroLKArIaZLLAluhx3LQGnkewGFjv"></script>
        <script type="text/javascript" src="{% static 'assets/js/amazeui.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/app.js' %}" ></script>
		<script type="text/javascript" src="{% static 'assets/js/blockUI.js' %}" ></script>
		<script type="text/javascript" src="{% static 'assets/js/charts/echarts.min.js' %}" ></script>
		<script type="text/javascript" src="{% static 'assets/js/charts/indexChart.js' %}" ></script>
		
	</head>
	<body>
		<!-- Begin page -->
		<header class="am-topbar am-topbar-fixed-top">		
			<div class="am-topbar-left am-hide-sm-only">
                <a href="{% url 'gis:index' %}" class="logo"><span>南工GIS</span><i class="zmdi zmdi-layers"></i></a>
            </div>
	        <div class="contain">
				<ul class="am-nav am-navbar-nav am-navbar-left">

					<li><h4 class="page-title">{% block title%}{% endblock title %}</h4></li>
				</ul>
				
				
			</div>
			
		</header>
		<!-- end page -->
		
		
		<div class="admin">
		    {% include 'gis/left.html' %}
		<!-- ========== Left Sidebar end ========== -->
	    
		<!-- Start right Content here -->
		    {% block content%}{% endblock content %}
		</div>
		
		
		
	</body>
	
</html>

templates/gis/left.html
{% load staticfiles %}
<div class="admin-sidebar am-offcanvas am-padding-0" id="admin-offcanvas">
				    <div class="am-offcanvas-bar admin-offcanvas-bar">
				    	<!-- User -->
						<div class="user-box am-hide-sm-only">
	                        <div class="user-img">
	                            <img src="{% static 'assets/img/index.jpg' %}" alt="user-img" title="Mat Helme" class="img-circle img-thumbnail img-responsive">
	                        </div>
	                        
	                    </div>
	                    <!-- End User -->
	            
						 <ul class="am-list admin-sidebar-list">
						    
						    <li class="admin-parent">
						      <a class="am-cf" data-am-collapse="{target: '#collapse-nav1'}"><span class="am-icon-table"></span> 功能 <span class="am-icon-angle-right am-fr am-margin-right"></span></a>
						      <ul class="am-list am-collapse admin-sidebar-sub am-in" id="collapse-nav1">
						        <li><a href="{% url 'gis:index' %}" class="am-cf"> 概况</span></a></li>
						        <li><a href="{% url 'gis:route_plan' %}" class="am-cf"> 线路规划</span></a></li>
						        <li><a href="{% url 'gis:search' %}">地点搜索</a></li>
						      </ul>
						    </li>
						    
						    <li class="admin-parent">
						      <a class="am-cf" data-am-collapse="{target: '#collapse-nav5'}"><span class="am-icon-file"></span> 管理 <span class="am-icon-angle-right am-fr am-margin-right"></span></a>
						      <ul class="am-list am-collapse admin-sidebar-sub am-in" id="collapse-nav5">
						        <li><a href="{% url 'gis:add_marker1' %}" class="am-cf"> 输入地名增加地点</a></li>
						        <li><a href="{% url 'gis:add_marker2' %}" class="am-cf"> 取点增加地点</a></li>
						        <li><a href="{% url 'gis:data_admin' %}">后台管理</a></li>
						      </ul>
						    </li>
						  </ul>
				    </div>
				  </div>

templates/gis/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title></title>	
		<link rel="stylesheet" href="../assets/css/core.css" />
		<link rel="stylesheet" href="../assets/css/menu.css" />
		<link rel="stylesheet" href="../assets/css/amazeui.css" />
		<link rel="stylesheet" href="../assets/css/component.css" />
		<link rel="stylesheet" href="../assets/css/page/form.css" />
	</head>
	<body>
		<div class="account-pages">
			<div class="wrapper-page">
				<div class="text-center">
	                <a href="index.html" class="logo"><span>Admin<span>to</span></span></a>
	            </div>
	            
	            <div class="m-t-40 card-box">
	            	<div class="text-center">
	                    <h4 class="text-uppercase font-bold m-b-0">Sign In</h4>
	                </div>
	                <div class="panel-body">
	                	<form class="am-form">
	                		<div class="am-g">
	                			<div class="am-form-group">
							      <input type="email" class="am-radius"  placeholder="Username">
							    </div>
							
							    <div class="am-form-group form-horizontal m-t-20">
							      <input type="password" class="am-radius"  placeholder="Password">
							    </div>
							    
							    <div class="am-form-group ">
		                           	<label style="font-weight: normal;color: #999;">
								        <input type="checkbox" class="remeber"> Remember me
								    </label>
		                        </div>
		                        
		                        <div class="am-form-group ">
		                        	<button type="button" class="am-btn am-btn-primary am-radius" style="width: 100%;height: 100%;">Log In</button>
		                        </div>
		                        
		                        <div class="am-form-group ">
		                        <a href="page-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> Forgot your password?</a>
		                        </div>
	                		</div>

	                	</form>
							
	                </div>
	            </div>
			</div>
		</div>
	</body>
</html>

templates/gis/map.html
{% extends 'gis/indexDemo.html' %}
{% block title%}概况{% endblock title %}
{% block content %}
<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="am-g">
					<!-- Row start -->
						
				</div>
				
				
				
				<div class="am-g">
					<div class="am-u-md-8">	
						<!--<img style="margin:0px" src="http://api.map.baidu.com/staticimage/v2?ak=fvFZIqg49Onsp6huTcfKbN7mXeaFQRRZ&width=500&height=300&zoom=16&scale=2&center=南昌工程学院"></img>
						<img style="margin:0px" src="{{map.src}}"></img>
						-->
						<div style="width:680px;height:550px;border:#ccc solid 1px;font-size:12px" id="map"></div>
							
					</div>
					
					<div class="am-u-md-4">
				        {% block right %}
				        {% endblock right %}		
				    </div>
				    

			    </div>
		</div>
		<!-- end right Content here -->
		</div>
<script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
	<script>
	$(document).ready(function(){
      
      // 列表 list
      /*function(){
          $.getJSON("{% url 'gis:get_marker' %}",function(ret){
            //返回值 ret 在这里是一个列表
            for (var i = ret.length - 1; i >= 0; i--) {
              // 把 ret 的每一项显示在网页上
              $('#list_result').append(' ' + ret[i])
            };
          })
      }*/
 
      //创建和初始化地图函数：
    function initMap(){
      createMap();//创建地图
      setMapEvent();//设置地图事件
      addMapControl();//向地图添加控件
      addMapOverlay();//向地图添加覆盖物
    }
    function createMap(){ 
      map = new BMap.Map("map",{ enableMapClick: false }); 
      map.centerAndZoom(new BMap.Point(116.038624,28.695625),16);
      map.setMaxZoom(18);
      map.setMinZoom(16);
      
      if (enableGetPoint == 1){
        map.addEventListener("click",function(e){
            //alert(e.point.lng + "," + e.point.lat);
            $("#lngview").html(e.point.lng);
            $("#latview").html(e.point.lat);
            $("#lng").val(e.point.lng);
            $("#lat").val(e.point.lat);
        });
      }
    }
    function setMapEvent(){
      map.enableScrollWheelZoom();
      map.enableKeyboard();
      map.enableDragging();
      map.enableDoubleClickZoom()
    }
    function addClickHandler(target,window){
      target.addEventListener("click",function(){
        target.openInfoWindow(window);
      });
      
    }
    /*
    function addMapOverlay(){
      var markers = [
        {content:"我的备注",title:"我的标记",imageOffset: {width:0,height:3},position:{lat:28.698136,lng:116.038462}}
      ];
      
      for(var index = 0; index < markers.length; index++ ){
        var point = new BMap.Point(markers[index].position.lng,markers[index].position.lat);
        var marker = new BMap.Marker(point,{icon:new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png",new BMap.Size(20,25),{
          imageOffset: new BMap.Size(markers[index].imageOffset.width,markers[index].imageOffset.height)
        })});
        var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
        var opts = {
          width: 200,
          title: markers[index].title,
          enableMessage: false
        };
        var infoWindow = new BMap.InfoWindow(markers[index].content,opts);
        marker.setLabel(label);
        addClickHandler(marker,infoWindow);
        map.addOverlay(marker);
      };
    }*/

    function addMapOverlay(){
      $.getJSON("{% url 'gis:get_marker' %}",function(markers){
        //测试是否成功加载内容
        //alert(markers[0].title)
        for(var index = 0; index < markers.length; index++ ){
          var point = new BMap.Point(markers[index].lng,markers[index].lat);
          var marker = new BMap.Marker(point);
          
          //新建文字标注
          //var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
          var opts = {
            width: 200,
            title: markers[index].title,
            enableMessage: false
          };
          var infoWindow = new BMap.InfoWindow(markers[index].content,opts);
          
          //设置文字标注
          //marker.setLabel(label);
          addClickHandler(marker,infoWindow);
          map.addOverlay(marker);
          };
      }) 
    }
    
    //向地图添加控件
    function addMapControl(){
      
      var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
      scaleControl.setUnit(BMAP_UNIT_METRIC);
      map.addControl(scaleControl);
      var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_RIGHT,type:0});
      map.addControl(navControl);
      var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:true});
      map.addControl(overviewControl);
    }
    var map;
    var enableGetPoint = {{enableGetPoint}};
    initMap();
    if(enableGetPoint == 1){
        myValue = '';
	    loadMapAutocomplete("title");
        function G(id) {
            return document.getElementById(id);
        }

        function loadMapAutocomplete(title) {
            var checkValue;
            Ac = new BMap.Autocomplete( //建立一个自动完成的对象
                {
                    "input": title,
                }
            );
            Ac.addEventListener("onconfirm", function(e) {    //鼠标点击下拉列表后的事件
	        var _value = e.item.value;
	        
	    	myValue = _value.street +  _value.business;
	    	$("#title").val(myValue);
	    });
        
        }
    }
    
});
    
  </script>
{% endblock content %}

templates/gis/right.html
{% extends 'gis/map.html' %}
{% block title %}增加地点{% endblock title%}
{% block right %}
<div class="card-box">
	<h4 class="header-title m-t-0 m-b-30">增加地点</h4>
		<form class="am-form">
		    
			<div class="am-form-group">
				<label >地点名字</label>
				<input id="title" type="text" class="am-radius" placeholder="输入地名/建筑物名字">
				<label>点击地图相应位置获得经纬度</label>
				<br>
				<label>经度:<span id="lngview"></span></label>
				<br>
				<label>纬度:<span id="latview"></span></label>
				<input id="lng" type="hidden">
				<input id="lat" type="hidden">
				<textarea class="am-u-md-10 form-control" rows="5" id="content" placeholder="输入地点的介绍/描述"></textarea>
			</div>
		    <button type="button" onclick="add();">增加</button>
		    <span id="status"></span>
	    </form>
</div>
<script>
function add(){
    var title = $("#title").val();
    //var title = myValue;
    //if (title === ''){
    //    title.$("#title").val();
    //}
    var lng = $("#lng").val();
    var lat = $("#lat").val();
    var content = $("#content").val();
    //alert(title + "," + lng + "," + lat + "," + content)
    alert(title)
    if(title != "" && content != "" && lng != "" && lat != ""){
        $.post(
        "{% url 'gis:add' %}",
        {'title':title,'lng':lng,'lat':lat,'content':content}, 
        function(ret){
            if(ret.status === 'True'){
                $('#status').html(ret.message);
                location.reload();
            }
            else{
                $('#status').html(ret.message);
            }
        }
        )
    }
    else{
        alert("请输入完整信息");
    }
    
}
</script>
{% endblock right %}

templates/gis/search_main.html
{% extends 'gis/indexDemo.html' %}

{% block content %}
<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="am-g">
					<!-- Row start -->
						
				</div>
				
				
				
				<div class="am-g">
					<div class="am-u-md-8">	
						<!--<img style="margin:0px" src="http://api.map.baidu.com/staticimage/v2?ak=fvFZIqg49Onsp6huTcfKbN7mXeaFQRRZ&width=500&height=300&zoom=16&scale=2&center=南昌工程学院"></img>
						<img style="margin:0px" src="{{map.src}}"></img>
						-->
						<div style="width:670px;height:550px;border:#ccc solid 1px;font-size:12px" id="map"></div>
							
					</div>
					
					<div class="am-u-md-4">
				        {% block right %}
				        {% endblock right %}		
				    </div>
				    

			    </div>
		</div>
		<!-- end right Content here -->
		</div>
 
{% endblock content %}